# This demo workflow will 
## - perform a code scan using GHAS
## - build a container from dockerfile
## - push the docker image to Azure container registry
## - Login to target Azure environment
## - Query for all resources inside the sub
#
# Secret scanning happens at commit time.
# The code QL is performed at build time
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#   - AZURE_RBAC_CREDENTIALS
#   - REGISTRY_USERNAME
#   - REGISTRY_PASSWORD
# 2. Change env variables for your configuration.

# references:
##   - GitHub Actions for Azure: https://github.com/Azure/Actions
##   - Azure Service Principal for RBAC: https://github.com/Azure/functions-action#using-azure-service-principal-for-rbac-as-deployment-credential
## variables https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
## https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts


name: CICD Workflow MVP Demo

## triggers
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push: 
    branches: [main]

## set env variables 
env:
  LOGIN_SERVER: 'usecase1234registry.azurecr.io'              # set this to login server for your private container registry (e.g. 'contoso.azurecr.io', 'index.docker.io' )
  REGISTRY: 'usecase1234registry'                 # set this to proper value for REGISTRY
  NAMESPACE: 'logistics'               # set this to proper value for NAMESPACE
  IMAGE: 'simulation'                       # set this to proper value for IMAGE
  TAG: $GITHUB_RUN_NUMBER                           # set this to proper value for TAG
  DOCKERFILE: 'docker/emptycontainer.dockerfile'
  RG: 'devsecopscicdtestRG'

## jobs run in parallel by default unless otherwise specified
jobs:

  scan-code:
    strategy:
      matrix:
        language: [ 'python' ]
    uses: ./.github/workflows/perform-code-scan.yml
    with: 
      language: ${{ matrix.language }}

  copy-publish:
    name: Publish IaC Artifacts to artifact storage
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app # optional, default is artifact
        path: |
          docker
          python

  build-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    environment: dev
    # environment: AzureUSGovernment
    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Build Docker Image'
      shell: bash
      run: |
        echo 'Reference: https://docs.docker.com/engine/reference/builder/'
        pwd
        ls -la
        docker build -f ${{ env.DOCKERFILE }} . -t ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.TAG }}

    - name: 'Login to Azure Target Environment'
      run: |
        echo '::warning:: No connectivity to target env!!'

    - name: 'Login to Azure Container Registry via azcli'
      run: |
        echo '::warning:: No connectivity to container registry!!'

    - name: 'Push Docker Image to Container Registry'
      shell: bash
      run: |
        echo 'push docker image to container registry'
        echo "::warning:: Cannot push image to target registry!"
        # docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.TAG }}


  deploy-dev:
    if: ${{ github.event_name == 'push' }}
    needs: [copy-publish, build-push]
    name: Deploy to Dev and Run Validation
    runs-on: ubuntu-latest
    environment: dev
    steps:

    - name: Download published artifacts
      uses: actions/download-artifact@v3
      with:
        name: app

    - name: 'Login to Azure Target Environment'
      run: |
        echo '::warning:: No connectivity to target environment!!'

    - name: 'Deploy Infrastructure Resources via IaC'
      run: |
        echo '::warning:: No connectivity to target environment!!'
 
    - name: 'Login to Azure Container Registry'
      run: |
        echo '::warning:: No connectivity to container registry!!'

    - name: 'Deploy container'
      run: |
        echo '::warning:: Cannot create container instance!!'
        #az container create --resource-group $rg --name $name --image $image --dns-name-label $dnsname --ports 80

  deploy-test:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [deploy-dev]
    name: Deploy to Test and Run Validation
    runs-on: ubuntu-latest
    environment: test
    steps:

    - name: Download published artifacts
      uses: actions/download-artifact@v3
      with:
        name: app

    - name: 'Login to Azure Target Environment'
      run: |
        echo '::warning:: No connectivity to target environment!!'

    - name: 'Deploy Infrastructure Resources via IaC'
      run: |
        echo '::warning:: No connectivity to target environment!!'
 
    - name: 'Login to Azure Container Registry'
      run: |
        echo '::warning:: No connectivity to container registry!!'

    - name: 'Deploy container'
      run: |
        echo '::warning:: Cannot create container instance!!'
